### ISSUE TITLE
Agenda for 1/20/15 Meetup

### ISSUE THREAD

**Issue by Frymasterspeck** [codeisland/Code-Island-Admin#6]
Per core group meeting, let's please hash out the agenda for tomorrow's meetup so we can publicize it. From my notes:

New For This Meetup
- printouts of specific issues for work groups
- outreach to include specific projects/issues

Presentation Portion

[Ryan, please add...]

Work Portion

1. Data Visualization [specific issues(s)?]
2. Google Trekker - how to generate list of potential locations to document
3. Balance - can we stand it up in one night?
4. Domain infrastructure - emails req'd for chat functions; Github issues to project pages; map w/parking to website
5. Overflow - survey of city/town open data

**Comment by Frymasterspeck** [comment]
[Balance](https://github.com/codeforamerica/balance) - original repo from CfA

**Comment by joealba** [comment]
Balance looks neat. Who can get the RI integration info?

I will be at Product Hunt -- http://producthuntpvd.splashthat.com/.  Hope to stop by after.

**Comment by tomlancaster** [comment]
Balance does look neat, and I will also be at Product Hunt tomorrow,
although I'll also try to stop by afterwards.

On Mon, Jan 19, 2015 at 3:21 PM, Joe Alba <notifications@github.com> wrote:

> Balance looks neat. Who can get the RI integration info?
>
> I will be at Product Hunt -- http://producthuntpvd.splashthat.com/. Hope
> to stop by after.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeisland/Code-Island-Admin/issues/6#issuecomment-70554422>
> .
>



-- 
-------
Vice President, Engineering
InCrowd, Inc.

**Comment by joealba** [comment]
The Balance Google Doc (https://docs.google.com/spreadsheets/d/12jOXkz1bt7bHzhuXhHYdHhTd45IgrmyVg8-hw93BjIo/edit#gid=0) already had a phone number for RI.  I called it and started adding some rough notes, but now I'm stuck on needing an example card number.

**Comment by joealba** [comment]
This doc talks about adding a PIN, which may be a showstopper if it is required to check the balance.  http://www.dhs.ri.gov/Portals/0/Uploads/Documents/FormsApps/EBT14.pdf

**Comment by theryankelly** [comment]
@thomguertin I believe you were successful in reaching out to DHS to get an example user/pin.  Can you send along that information.

**Comment by paulrolfe** [comment]
I'm going to that too!

Paul Rolfe
paul.a.rolfe@gmail.com
Red Ostrich LLC || http://paulrolfe.com
CapitolBuddy: iOS App || http://capitolbuddy.com
http://twitter.com/capitolbuddy || http://Facebook.com/CapitolBuddy
<http://facebook.com/CapitolBuddy>

**Comment by nelsonri72** [comment]
Data viz agenda:
Sankey: Walk thru diagram/plan
Area: Update & discuss next steps

p.s. sorry for the delay

**Comment by theryankelly** [comment]
Related to #4 Infrastructure 
Need CFA branded one for Meetups
http://provplan.org/assets/uploads/fom/Directions_10DavolSq.pdf
